// <auto-generated />
using System;
using MetaSphere.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetaSphere.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322183217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MetaSphere.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 18, 32, 16, 28, DateTimeKind.Utc).AddTicks(6285),
                            Description = "A rare digital artifact from the genesis collection. Glowing neon patterns embedded in a quantum matrix.",
                            ImageUrl = "/images/nft1.png",
                            IsFeatured = true,
                            Rarity = "Legendary",
                            Tag = "Digital Asset",
                            Title = "Neon Genesis #001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 18, 32, 16, 28, DateTimeKind.Utc).AddTicks(6297),
                            Description = "Prime virtual real estate in the MetaSphere core district. Unlimited build potential.",
                            ImageUrl = "/images/nft2.png",
                            IsFeatured = true,
                            Rarity = "Rare",
                            Tag = "Virtual Land",
                            Title = "Virtual Land Alpha"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 18, 32, 16, 28, DateTimeKind.Utc).AddTicks(6300),
                            Description = "Next-gen avatar with full customization. Unlock exclusive metaverse zones.",
                            ImageUrl = "/images/nft3.png",
                            IsFeatured = true,
                            Rarity = "Epic",
                            Tag = "Avatar",
                            Title = "Cyber Avatar X"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 18, 32, 16, 28, DateTimeKind.Utc).AddTicks(6303),
                            Description = "Teleportation node connecting multiple metaverse realms. Limited edition.",
                            ImageUrl = "/images/nft4.png",
                            IsFeatured = false,
                            Rarity = "Limited",
                            Tag = "Utility",
                            Title = "Quantum Portal"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 18, 32, 16, 28, DateTimeKind.Utc).AddTicks(6306),
                            Description = "Wearable dark matter armor with stealth capabilities and energy shields.",
                            ImageUrl = "/images/nft5.png",
                            IsFeatured = false,
                            Rarity = "Rare",
                            Tag = "Wearable",
                            Title = "Dark Matter Suit"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 22, 18, 32, 16, 28, DateTimeKind.Utc).AddTicks(6309),
                            Description = "Create and broadcast holographic content across the MetaSphere network.",
                            ImageUrl = "/images/nft6.png",
                            IsFeatured = false,
                            Rarity = "Common",
                            Tag = "Digital Asset",
                            Title = "Hologram Studio"
                        });
                });

            modelBuilder.Entity("MetaSphere.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("MetaSphere.Models.Lead", b =>
                {
                    b.HasOne("MetaSphere.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
